version: "3.7"

services:

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    hostname: prometheus
    volumes:
      - ./configs/prometheus:/etc/prometheus/
    command:
      - --config.file=/etc/prometheus/config.yml
    ports:
      - "9090:9090"

  elasticsearch:
    image: elasticsearch:8.16.1
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks:
      - elk
    ports:
      - "9200:9200"

  logstash:
    image: logstash:8.10.2
    container_name: logstash
    hostname: logstash
    networks:
      - elk
    depends_on:
      - elasticsearch
    volumes:
      - ./configs/logstash/pipelines/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5001:5000"
      - "9600:9600"

  kibana:
    image: kibana:8.10.2
    container_name: kibana
    hostname: kibana
    networks:
      - elk
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"

networks:
  elk:
    driver: bridge