server:
  port: 8080

spring:
  application:
    name: homework-app
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/service_db
    username: t-fintech
    password: t-fintech
  jpa:
    properties:
      hibernate:
        show_sql: false
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/master.xml
  cache:
    cache-names: currencies-rates
    caffeine:
      spec: expireAfterAccess=1h

logging:
  level:
    root: info
    org.springframework.security: DEBUG
    org.hibernate:
      SQL: debug
      type.descriptor.sql.BasicBinder: warn

kudago-api:
  base-url: "https://kudago.com/public-api/v1.4"
  categories-path: "/place-categories"
  locations-path: "/locations"
  events-path: "/events"
  fill-cache:
    schedule: 3600
  parallel-requests:
    number: 5
    fair-access: true

cbr-api:
  base-url: http://www.cbr.ru
  currency:
    codes:
      path: /scripts/XML_valFull.asp
    daily-exchange-rates:
      path: /scripts/XML_daily.asp
      date-param: date_req

executors:
  threads-num:
    scheduled: 2
    fixed: 2

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        failureRateThreshold: 60
        minimumNumberOfCalls: 5
        registerHealthIndicator: true
        permittedNumberOfCallsInHalfOpenState: 10
    instances:
      central-bank-client:
        baseConfig: default
        waitDurationInOpenState: 20s

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
      show-details: "ALWAYS"
  health:
    circuitbreakers:
      enabled: true

security:
  jwt:
    secret: 6c112c14b1e753b71df3d7abd3c3ad0b31f43c3ab8f4595d70fbedd7ed76bb3b24c59409910a21bf363339ab58434f800beb489ab570f6ce15b7be41c6d56eb5
    expiration-time: 2592000000 # 30d